task: detect
img_size: 640
labels:
  0: trailer
  1: trailer_top
  2: tractor
  3: truck
  4: yard_mule
  5: empty_truck
  6: human
  7: trailer_id
  8: license_plate
  9: other_vehicle
confidence_threshold: 0.35
description: Object detection model for yard and logistics environments
model_v1:
  model_name: yard_sol_v12m_od
  jsons_dir: model_v1_json
  weights_file: Yard_sol-v12m-od-iter0-20251217-imgsz640.pt
  version: v12m_iter0
# model_v2:
#   model_name: yard_sol_v12m_od1
#   jsons_dir: model_v1_json
#   weights_file: Yard_sol-v12m-od-iter1-20251217-imgsz640.pt
#   version: v12m_iter1
# model_v3:
#   model_name: yard_sol_v12m_od2
#   jsons_dir: model_v1_json
#   weights_file: Yard_sol-v12m-od-iter2-20251217-imgsz640.pt
#   version: v12m_iter2

